version: '3.8'

services:
  backend:
    build:
      context: ./Corona-Graph-Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./Corona-Graph
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Corona-Graph:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
