version: '3.8'

services:
  backend:
    build: ./Corona-Graph-Backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build: ./Corona-Graph
    ports:
      - "5000:5000"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
